### ISSUE TITLE
Integrate multiple datasets

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#141]
There could be other Shareabouts datasets, possibly hosted on different API's, or under different datasets on our own API (i.e. trees, noise, air), and we want to integrate them with our Hey Duwamish flavor.

We need a way to seemlessly load these datasets into a single Shareabouts map.

**Comment by LukeSwart** [comment]
As mentioned above, we want to control mulitiple datasets within a single flavor. This implementation has been partially implemented with our ability to rename the `/place` prefix in our url with any arbitrary name, like `/:dataset`, in our router as shown here: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/routes.js#L11-L14 

For reference, our Backbone places collection is instantiated here: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/routes.js#L62 and the collection itself is defined here: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/models.js#L246 And http://backbonejs.org/ is a good reference for how Backbone models and Backbone collections work as well. For example, the Backbone router documentation, which may help with the paragraph above, is here: http://backbonejs.org/#Router-routes

We currently have our Backbone collection of Shareabouts places in our app view here: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/views/app-view.js#L44 (which is made available when we pass it to `this.collection` from our router). So we will need to manage multiple Backbone collections - one collection per dataset - which we should probably implement using a hash map of collections. For example, each collection can be defined as a layer in our config, where we can specify the API endpoint of the dataset that we need to load. By implementing our hash of collections, we can easily retrieve and control our collections in a single data structure. Note that we will have to refactor this new "hash map of collections" into our map view as well.

When we implement this new functionality, we will also have to update our `viewPlace` method (and ideally our `viewLandmark` method as well), which handles our `/:dataset/:id` route. We are not currently using the `:dataset` parameter, as shown here: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/routes.js#L149-L153 But you can see how we would want to pass in the `:dataset` param (as `datasetSlug`), and use that to fetch the correct collection within our app view. After that, we should be able to view the place as normal.

Here is the `viewPlace` method: https://github.com/smartercleanup/platform/blob/master/src/sa_web/static/js/views/app-view.js#L639-L733  and the `viewLandmark` method is right before it.

Of course, other issues may come up, so feel free to get in touch!

On a side note, there will probably be a little extra complexity when an API key is required, because we probably don't want to publish it publicly in our config. We may specify the name of the environment variable in our config, then load the API keys from our environment variable in our Backbone model or Backbone view.

**Comment by LukeSwart** [comment]
Resolved by PR #254
