### ISSUE TITLE
Put visual spotlight around place icon when selected on a map

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#166]
We need a better way to show that a place record is selected on the map.

When you select a place record on the map the icon gets bigger but does nothing else to indicate it's being selected.

Suggestions: make the icon glow, provide some sort of outline in addition to an increase in size.

**Comment by goldpbear** [comment]
I've noticed that it's a little strange for the spotlight not to re-center when the map is zoomed. When the user zooms the map the spotlight and its pin will drift apart. I'd suggest either re-centering the spotlight on zoom end, or just removing it entirely on zoom end. Does anyone have a preference for one or the other? Either of these options should be an easy change to make.

**Comment by LukeSwart** [comment]
Ah, yes, this has been resolved on the master branch! (we just haven't merged it in with develop)

I just pushed a hotfix to remove the spotlight when zoom is changed. But let me know if you find out other issues...

**Comment by goldpbear** [comment]
Ah, ok! Sounds good.

**Comment by LukeSwart** [comment]
Yeah, I just merge master back with develop to fix those changes. Just pull in the changes (ie `git checkout develop` and `git pull --rebase`) and rebase the develop branch (ie `git checkout goldpbear/my-branch` and `git rebase develop`) to resync with develop. You might have merge conflicts, but I'm sure you can handle them!

Also, I think this issue is resolved from PR #290 (thanks @goldpbear !)

Closing the issue - and if there are bugs, we can always make a new issue.
