### ISSUE TITLE
Enable satellite view for map tiles

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#190]
Looking at the map via satellite view really changes a lot about how the area can be analyzed and understood. I almost prefer it by default, though in certain instances it can reduce visibility.

We should either have a toggle or enable it by default because the difference is quite dramatic. It really is much more useful than the cartoon tiles.

**Comment by LukeSwart** [comment]
This was resolved in PR #319 so I am closing this for now.

BUT the implementation is a bit hackey because it requires our satellite basemap having the id `satellite` and our street-view basemap having the id `osm`. Ideally we would have some kind of radio button on our legend to toggle an arbitrary number of basemaps.
