### ISSUE TITLE
Editor: Support editable geometry

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#410]
We are only able to edit geometries from our admin interface. Editing via the admin interface is limited to changes to the geometry itself; geometry styles (stroke and fill colors, opacity) are not editable.

Let's try to make both geometries and geometry styles editable from the app.

**Comment by Bilal-io** [comment]
We should consider this [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) plugin. Here is a [demo](http://leaflet.github.io/Leaflet.draw/)

**Comment by goldpbear** [comment]
This seems pretty cool, and maybe preferable to geojson.io since it's a leaflet plugin?

**Comment by Bilal-io** [comment]
@goldpbear I think this plugin uses GeoJSON since they look very similar, I also did some [research in the file](https://github.com/Leaflet/Leaflet.draw/blob/272ebe022553a8eaf5c536a5df01e0e539524100/examples/libs/leaflet-src.js). But yes, this would be preferable, since most of the work will be already done by leaflet.draw team. we just have to implement it.
