### ISSUE TITLE
disable html5 geolocation for desktop devices

### ISSUE THREAD

**Issue by sethvincent** [smartercleanup/platform#59]
let's say i'm in the university district and allowed html5 geolocation to detect my location.

the map zooms/pans to my location. now i have to zoom out and pan around to get back to the duwamish area.

it would be cool if some combination of these things could happen:

- the js detects that i'm not on a mobile device and so doesn't automatically use html5 geolocation
- there's a `nearby` or `show my location` button or something like that which triggers the geolocation
- the map doesn't pan outside of the duwamish area when the geolocation happens

**Comment by LukeSwart** [comment]
Closing this issue, because we have disabled geolocation on start. Instead, we have a geolocation button in the top left, represented by a crosshair.

in re `the map doesn't pan outside of the duwamish area when the geolocation happens`, I'm not sure whether we want to restrict a user's ability to pan wherever they want. If it should be implemented, I think we should make a separate issue and discuss it in more depth there.
